### ISSUE TITLE
BackgroundLocation.getLocationUpdates when phone is locked

### ISSUE THREAD

**Issue by jaca420** [Almoullim/background_location#160]
My app writes to Firestore when location changes. I was testing it with app open and everything is ok. But when I lock my phone and leave the app open, I still see the notification "Background service is running" but nothing is written to the database. 
Does this not work with phone locked? 

```
      await BackgroundLocation.startLocationService(distanceFilter: 30);

      BackgroundLocation.getLocationUpdates((location) {
        setState(() {
          latitude = location.latitude.toString();
          longitude = location.longitude.toString();
          accuracy = location.accuracy.toString();
          altitude = location.altitude.toString();
          bearing = location.bearing.toString();
          speed = location.speed.toString();
        });

        processLocation(location);
      });
```

processLocation is just creating the database object and setting it.

**Comment by MoralCode** [comment]
if you put a print statement in or after the setState call, do you get it printing output? i.e. is it just the database part not working? or are you not getting any background location updates at all?

**Comment by Almoullim** [comment]
fixed in https://github.com/Almoullim/background_location/commit/52ef3db3e572596bb0e879dc57aa201fe160143e version 0.12.0

**Comment by MoralCode** [comment]
@Almoullim is this related to notification importance? the original PR said "I still see the notification "Background service is running"", which made me think it was more likely related to firestore

**Comment by Almoullim** [comment]
if it's not fixed as part of the notifcation importance then it would be related to one of these two issues: https://github.com/Almoullim/background_location/issues/139 https://github.com/Almoullim/background_location/issues/131 either way this issue is old and I doubt we'd hear back from the issue author to know more details so its best to close and focus on the other two. Please let me know if you think otherwise, maybe I'm missing something.
